version: "3"

services:
    elasticsearch:
      image: elasticsearch:7.6.1
      container_name: elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      volumes:
        - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      networks:
        - elk

    logstash:
      image: logstash:7.6.1
      container_name: logstash
      command: logstash -r -f /opt/logstash/config/logstash.conf
      ports:
        - "5044:5044"
        - "9600:9600"
      links:
        - kafka
        - elasticsearch
      volumes:
        - ./logstash/logstash.conf:/opt/logstash/config/logstash.conf
        - ./testdata/:/testdata/:ro
      environment:
        LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      networks:
        - elk

    zookeeper:
      image: wurstmeister/zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      networks:
        - elk      

    kafka:
      image: wurstmeister/kafka:2.12-2.3.0
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.17.0.1:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_CREATE_TOPICS: "test-topic"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./etcdata/kakfa:/kafka
      depends_on:
        - zookeeper
      networks:
        - elk
   
    kibana:
      image: kibana:7.6.1
      container_name: kibana
      ports:
        - "5601:5601"
      volumes:
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      environment:
        LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      links:
        - elasticsearch
      networks:
        - elk


volumes:
  example:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.184,nolock,soft,rw"
      device: ":/home/kd/pandora"


networks:
  elk:
    driver: overlay
    driver_opts:
      encrypted: "true" 
