version: "3"

services:
  sql:
    image: mysql:8.0.20
    container_name: kd-mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/kdlee/kdsql:/var/lib/mysql
